# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * 1-5'
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tests:
        description: 'Test Name'
        required: true
        default: 'test_login' 
        type: choice
        options:
        - test_login
        - test_login_front_manager
        - test_ 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
        # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo timedatectl set-timezone America/Bogota
          pip install pytest-playwright
          source venv/bin/activate
          pip install -r requirements.txt
          playwright install
          echo test, and deploy your project.

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pytest --html=test/report/report.html --self-contained-html --numprocesses 4 -k "test_login"
        
      # Publish HTML report
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: HTML-report
          path: test/report/
                
                
      # Publish HTML report as page          
      - name: "Publish test results"
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v3.7.3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './test/report'
          keep_files: true
          
          
      
          
