name: Python unittest

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    
    # Runs a set of commands using the runners shell
    - name: Run script install dependency
      run: |
        sudo timedatectl set-timezone America/Bogota
        source venv/bin/activate
        pip install -r requirements.txt
        
      # Runs a single command using the runners shell
    - name: Run script unittest
      run: python -m unittest discover \src
